[project]
name = "bencode"
version = "0.1.0"
description = "a fork of Celend/bencode: python 3 bencode, support UTF-8 and read/write BT torrent file."
authors = [
    {name = "Celend", email = "forevertjt@gmail.com"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
license = {text = "LGPL-3.0-or-later"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
Documentation = "https://github.com/phanirithvij/bencode#readme"
Issues = "https://github.com/phanirithvij/bencode/issues"
Source = "https://github.com/phanirithvij/bencode"

[tool.hatch.version]
path = "src/bencode/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
